pull_request_rules:
  - name: Merge pull requests from dependabot if CI passes
      conditions:
        - author=dependabot[bot]
        - status-success=build
      actions:
        merge:
          method: squash
          commit_message: title+body
          strict: smart
          strict_method: merge
  - name: Automatic merge on approval and successful build
    actions:
      merge:
        method: squash
        commit_message: title+body
        strict: smart
        strict_method: merge
      delete_head_branch: {}
    conditions:
      - "#approved-reviews-by>=1"
      - status-success=build