apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  managedFields:
  - apiVersion: rbac.authorization.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:rules: {}
  name: emr-containers
  namespace: {{NAMESPACE}}
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  - services
  - configmaps
  - events
  - pods
  - pods/log
  verbs:
  - get
  - list
  - watch
  - describe
  - create
  - edit
  - delete
  - deletecollection
  - annotate
  - patch
  - label
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - patch
  - delete
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  - deployments
  verbs:
  - get
  - list
  - watch
  - describe
  - create
  - edit
  - delete
  - annotate
  - patch
  - label
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
  - describe
  - create
  - edit
  - delete
  - annotate
  - patch
  - label
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
  - describe
  - create
  - edit
  - delete
  - annotate
  - patch
  - label
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  verbs:
  - get
  - list
  - watch
  - describe
  - create
  - edit
  - delete
  - deletecollection
  - annotate
  - patch
  - label
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  managedFields:
  - apiVersion: rbac.authorization.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:roleRef:
        f:apiGroup: {}
        f:kind: {}
        f:name: {}
      f:subjects: {}
  name: emr-containers
  namespace: {{NAMESPACE}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: emr-containers
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: emr-containers