# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

apiVersion: v1
kind: Pod

spec:
  tolerations:
  - key: node-lifecycle
    operator: Equal
    value: spot
    effect: NoSchedule
  nodeSelector:
    node-lifecycle: spot
    spark-role: executor
    role: shared