apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: shared-driver-{{az}}
spec:
  # References cloud provider-specific custom resource, see your cloud provider specific documentation
  providerRef:
    name: shared-driver-nodes-{{az}}

  # Labels are arbitrary key-values that are applied to all nodes
  labels:
    role: shared
    node-lifecycle: on-demand
    spark-role: driver

  # Requirements that constrain the parameters of provisioned nodes.
  # These requirements are combined with pod.spec.affinity.nodeAffinity rules.
  # Operators { In, NotIn } are supported to enable including or excluding values
  requirements:
    # Include general purpose instance families
    - key: "karpenter.k8s.aws/instance-category"
      operator: In
      values: ["m"]
    - key: "kubernetes.io/arch"
      operator: In
      values: ["arm64"]
    # Exclude smaller instance sizes
    - key: "karpenter.k8s.aws/instance-size"
      operator: NotIn
      values: [nano, micro, small]
    - key: "karpenter.sh/capacity-type" # If not included, the webhook for the AWS cloud provider will default to on-demand
      operator: In
      values: ["on-demand"]
    - key: "topology.kubernetes.io/zone"
      operator: In
      values: ["{{az}}"]
    - key: "karpenter.k8s.aws/instance-hypervisor"
      operator: In
      values: ["nitro"]

  # Resource limits constrain the total size of the cluster.
  # Limits prevent Karpenter from creating new instances once the limit is exceeded.
  limits:
    resources:
      cpu: "100"
      memory: 100Gi

  # Priority given to the provisioner when the scheduler considers which provisioner
  # to select. Higher weights indicate higher priority when comparing provisioners.
  # Specifying no weight is equivalent to specifying a weight of 0.
  weight: 10
  
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: shared-driver-nodes-{{az}}
spec:
  amiFamily: AL2
  subnetSelector:
     aws-ids: {{subnet-id}}
  securityGroupSelector:
    karpenter.sh/discovery: {{cluster-name}}
  tags:
    KarpenerProvisionerName: "shared-driver"
  userData: |
    MIME-Version: 1.0
    Content-Type: multipart/mixed; boundary="BOUNDARY"

    --BOUNDARY
    Content-Type: text/x-shellscript; charset="us-ascii"

    #!/bin/bash
    yum install -y https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm,
    systemctl enable amazon-ssm-agent,
    systemctl start amazon-ssm-agent,

    --BOUNDARY--