name: Auto-approve Dependabot
on:
  pull_request_target

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/auto-approve-action@v2.1.0
      if: github.event.pull_request.user.login == 'dependabot[bot]'
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"