name: E2E
on:
  pull_request: {}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # needed to interact with GitHub's OIDC Token endpoint.
      contents: read
    strategy:
      matrix:
        suite: [data-lake, synchronous, emr-eks-cluster]
      fail-fast: false
    env:
      CI: "true"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Setup Node 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Setup Java 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu' # OpenJDK
          java-version: '11'
      - name: Install dependencies
        run: cd core && yarn install --check-files --frozen-lockfile
      - name: Set git identity
        run: |-
          git config user.name "Automation"
          git config user.email "github-actions@github.com"
      - name: Build
        run: cd core && npx projen build
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.6.1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_TO_ASSUME }}
          aws-region: us-east-1
      - name: E2E
        run: cd core && npx jest --group=integ/${{ matrix.suite }}/
    container:
      image: jsii/superchain:1-buster-slim-node14
